module.exports = (grunt) ->
  require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

  grunt.initConfig
    clean: "dest"
    browserify:
      dist:
        files:
          "public/js/migawari.js" : ["node_modules/migawari/index.js"]
    'gh-pages':
      public:
        options:
          base: "public"
          message: "Generated by grunt"
        src: "**/**"
    connect:
      server:
        options:
          port: 7777
          base: 'public'
          keepalive :true
          hostname: '*'
