module.exports = (grunt) ->
  require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

  config = {
    clean: ["public"]
    jade:
      src:
        files: [
          expand: true
          cwd: "src/views/"
          src: "**/*.jade"
          dest: "public"
          ext: ".html"
        ]
    stylus:
      src:
        files: [
          expand: true
          cwd: "src/assets"
          src: "css/**/*.styl"
          dest: "public"
          ext: ".css"
        ]
    copy:
      src:
        files:[
          expand: true
          cwd: "src/assets"
          src: "js/**/*.js"
          dest: "public"
          
        ]
    connect:
      server:
        options:
          port: 7777
          base: 'public/'
          keepalive :true
          hostname: '*'
          middleware: (connect, options) ->
            return [
              require('connect-livereload')({
                port: config.watch.public.options.livereload
              }),
              connect.static(options.base[0])
            ];
    watch:
      src:
        files: 'src/**/*'
        tasks: 'compile'
      public:
        files: [
          'public/**/*',
          '!public/bower_components/**/*'
        ]
        options:
          livereload: 35729
    open:
      server:
        path: 'http://localhost:<%%= connect.server.options.port %>'
    browserify:
      dist:
        files:
          "public/js/client.js" : ["lib/client.js"]
    'gh-pages':
      public:
        options:
          base: "public"
          message: "Generated by grunt"
        src: "**/**"
  }
  grunt.initConfig config
  grunt.registerTask 'compile', ['jade', 'stylus', 'copy', 'browserify']
  grunt.registerTask 'server', ['compile', 'connect','watch']